name: share_novel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^1.2.0
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_otp_text_field: ^1.1.1
  animated_bottom_navigation: ^0.0.5
  image_picker: ^1.0.7
  flutter_custom_carousel_slider: ^1.2.0
  shimmer: ^3.0.0
  carbon_icons: ^0.0.1+2
  flutter_tts: ^3.8.5
  animated_text_kit: ^4.2.2
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/